### ISSUE TITLE
An unexpected error occurred when I use Generate test for method 

### ISSUE THREAD

**Issue by zhangfj88** [wrdv/testme-idea#53]
![image](https://github.com/user-attachments/assets/b2f36834-89a6-45a4-ad82-ea764db27da3)
An unexpected error occurred when I use Generate test for method for an existing test
The detailed error information is as follows：
at com.weirddev.testme.intellij.utils.AccessLevelReflectionUtils.getField(AccessLevelReflectionUtils.java:17)
at com.weirddev.testme.intellij.generator.VelocityInitializer.getRuntimeInstance(VelocityInitializer.java:39)
at com.weirddev.testme.intellij.generator.VelocityInitializer.verifyRuntimeSetup(VelocityInitializer.java:21)
at com.weirddev.testme.intellij.generator.TestMeGenerator.createTestClassFromCodeTemplate(TestMeGenerator.java:126)
at com.weirddev.testme.intellij.generator.TestMeGenerator.createTestClass(TestMeGenerator.java:110)
at com.weirddev.testme.intellij.generator.TestMeGenerator$1$1.compute(TestMeGenerator.java:66)

**Comment by zhangfj88** [comment]
I will try to solve this problem in the near future。
